bundler_args: --without development
language: ruby
rvm:
  - "2.0.0"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - RAILS_ENV=test bundle exec rake db:create db:schema:load